# Generated by Django 2.2.6 on 2019-12-03 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DropboxLocation",
            fields=[
                (
                    "location_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("location_name", models.CharField(max_length=1024)),
                ("address", models.CharField(max_length=1024)),
                ("city", models.CharField(max_length=1024)),
                ("state_code", models.CharField(max_length=2)),
                ("zip", models.CharField(blank=True, max_length=5)),
                ("dates_hours", models.CharField(max_length=1024)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="EarlyVoteLocation",
            fields=[
                (
                    "location_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("location_name", models.CharField(max_length=1024)),
                ("address", models.CharField(max_length=1024)),
                ("city", models.CharField(max_length=1024)),
                ("state_code", models.CharField(max_length=2)),
                ("zip", models.CharField(blank=True, max_length=5)),
                ("dates_hours", models.CharField(max_length=1024)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="PollingLocation",
            fields=[
                (
                    "location_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("location_name", models.CharField(max_length=1024)),
                ("address", models.CharField(max_length=1024)),
                ("city", models.CharField(max_length=1024)),
                ("state_code", models.CharField(max_length=2)),
                ("zip", models.CharField(blank=True, max_length=5)),
                ("dates_hours", models.CharField(max_length=1024)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Precinct",
            fields=[
                (
                    "van_precinct_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("state_code", models.CharField(max_length=2)),
                ("county", models.CharField(max_length=1024)),
                ("fips", models.CharField(max_length=1024)),
                ("precinct_code", models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="Zip9ToPrecinct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zip9", models.CharField(max_length=9)),
                ("state_code", models.CharField(max_length=2)),
                (
                    "precinct",
                    models.ForeignKey(
                        db_column="van_precinct_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.Precinct",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StreetSegment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=1024)),
                ("street_number", models.CharField(max_length=1024)),
                ("street_pre_dir", models.CharField(blank=True, max_length=1024)),
                ("street_name", models.CharField(max_length=1024)),
                ("street_type", models.CharField(blank=True, max_length=1024)),
                ("street_post_dir", models.CharField(blank=True, max_length=1024)),
                ("city", models.CharField(max_length=1024)),
                ("state_code", models.CharField(max_length=2)),
                ("zip", models.CharField(max_length=9)),
                (
                    "precinct",
                    models.ForeignKey(
                        db_column="van_precinct_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.Precinct",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrecinctToPollingLocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_code", models.CharField(max_length=2)),
                ("distance", models.FloatField()),
                (
                    "polling_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.PollingLocation",
                    ),
                ),
                (
                    "precinct",
                    models.ForeignKey(
                        db_column="van_precinct_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.Precinct",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="PrecinctToEVLocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_code", models.CharField(max_length=2)),
                ("distance", models.FloatField()),
                (
                    "early_vote_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.EarlyVoteLocation",
                    ),
                ),
                (
                    "precinct",
                    models.ForeignKey(
                        db_column="van_precinct_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.Precinct",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="PrecinctToDropboxLocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_code", models.CharField(max_length=2)),
                ("distance", models.FloatField()),
                (
                    "dropbox_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.DropboxLocation",
                    ),
                ),
                (
                    "precinct",
                    models.ForeignKey(
                        db_column="van_precinct_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.Precinct",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
