# Generated by Django 2.2.6 on 2019-12-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0003_big_int_location_id")]

    operations = [
        migrations.AlterField(
            model_name="precinct",
            name="fips",
            field=models.CharField(blank=True, max_length=1024),
        )
    ]
