# Generated by Django 2.2.6 on 2019-12-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0004_fips_blank")]

    operations = [
        migrations.AlterField(
            model_name="dropboxlocation",
            name="state_code",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="dropboxlocation",
            name="zip",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="earlyvotelocation",
            name="state_code",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="earlyvotelocation",
            name="zip",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="pollinglocation",
            name="state_code",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="pollinglocation",
            name="zip",
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
