# Generated by Django 2.2.6 on 2019-12-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0005_column_length")]

    operations = [
        migrations.AlterField(
            model_name="dropboxlocation",
            name="address",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="dropboxlocation",
            name="city",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="dropboxlocation",
            name="dates_hours",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="dropboxlocation",
            name="location_name",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="dropboxlocation",
            name="state_code",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="dropboxlocation",
            name="zip",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="earlyvotelocation",
            name="address",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="earlyvotelocation",
            name="city",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="earlyvotelocation",
            name="dates_hours",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="earlyvotelocation",
            name="location_name",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="earlyvotelocation",
            name="state_code",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="earlyvotelocation",
            name="zip",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="pollinglocation",
            name="address",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="pollinglocation",
            name="city",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="pollinglocation",
            name="dates_hours",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="pollinglocation",
            name="location_name",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="pollinglocation",
            name="state_code",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="pollinglocation",
            name="zip",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
