# Generated by Django 2.2.6 on 2019-12-12 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0006_nullable_fields_location")]

    operations = [
        migrations.AlterField(
            model_name="precincttodropboxlocation",
            name="dropbox_location",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.DropboxLocation",
            ),
        ),
        migrations.AlterField(
            model_name="precincttodropboxlocation",
            name="precinct",
            field=models.ForeignKey(
                db_column="van_precinct_id",
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.Precinct",
            ),
        ),
        migrations.AlterField(
            model_name="precincttoevlocation",
            name="early_vote_location",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.EarlyVoteLocation",
            ),
        ),
        migrations.AlterField(
            model_name="precincttoevlocation",
            name="precinct",
            field=models.ForeignKey(
                db_column="van_precinct_id",
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.Precinct",
            ),
        ),
        migrations.AlterField(
            model_name="precincttopollinglocation",
            name="polling_location",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.PollingLocation",
            ),
        ),
        migrations.AlterField(
            model_name="precincttopollinglocation",
            name="precinct",
            field=models.ForeignKey(
                db_column="van_precinct_id",
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.Precinct",
            ),
        ),
        migrations.AlterField(
            model_name="streetsegment",
            name="precinct",
            field=models.ForeignKey(
                db_column="van_precinct_id",
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.Precinct",
            ),
        ),
        migrations.AlterField(
            model_name="zip9toprecinct",
            name="precinct",
            field=models.ForeignKey(
                db_column="van_precinct_id",
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.Precinct",
            ),
        ),
    ]
