# Generated by Django 2.2.6 on 2019-12-17 20:14

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0007_drop_fks")]

    operations = [
        migrations.CreateModel(
            name="SearchLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("success", models.BooleanField()),
                ("search_status", models.CharField(max_length=1024)),
                ("address_entered", django.contrib.postgres.fields.jsonb.JSONField()),
                ("autocomplete_selected", models.BooleanField(null=True)),
                ("heap_id", models.CharField(max_length=1024, null=True)),
                (
                    "precinct",
                    models.ForeignKey(
                        blank=True,
                        db_column="van_precinct_id",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.Precinct",
                    ),
                ),
            ],
        )
    ]
