# Generated by Django 2.2.6 on 2019-12-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0008_searchlog")]

    operations = [
        migrations.RemoveField(model_name="searchlog", name="address_entered"),
        migrations.AddField(
            model_name="searchlog",
            name="search_string",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="searchlog",
            name="city",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="searchlog",
            name="state_code",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="searchlog",
            name="street",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="searchlog",
            name="street_number",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="searchlog",
            name="zip5",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="searchlog",
            name="zip9",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
