# Generated by Django 2.2.6 on 2019-12-19 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0009_search_log_address_fields")]

    operations = [
        migrations.AlterField(
            model_name="searchlog",
            name="precinct",
            field=models.ForeignKey(
                blank=True,
                db_column="van_precinct_id",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app.Precinct",
            ),
        )
    ]
