# Generated by Django 2.2.6 on 2019-12-19 04:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0010_change_fk_cascade")]

    operations = [
        migrations.AddField(
            model_name="searchlog",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        )
    ]
