# Generated by Django 2.2.6 on 2020-01-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0011_searchlog_created_at")]

    operations = [
        migrations.AlterField(
            model_name="zip9toprecinct",
            name="zip9",
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AddConstraint(
            model_name="precincttodropboxlocation",
            constraint=models.UniqueConstraint(
                fields=("dropbox_location", "precinct"),
                name="unique_precinct_dropbox_location",
            ),
        ),
        migrations.AddConstraint(
            model_name="precincttoevlocation",
            constraint=models.UniqueConstraint(
                fields=("early_vote_location", "precinct"),
                name="unique_precinct_ev_location",
            ),
        ),
        migrations.AddConstraint(
            model_name="precincttopollinglocation",
            constraint=models.UniqueConstraint(
                fields=("polling_location", "precinct"),
                name="unique_precinct_polling_location",
            ),
        ),
        migrations.AddConstraint(
            model_name="streetsegment",
            constraint=models.UniqueConstraint(
                fields=("address", "city", "state_code", "zip"),
                name="unique_addr_city_state_zip",
            ),
        ),
    ]
