# Generated by Django 2.2.6 on 2020-01-09 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0012_unique_constraints")]

    operations = [
        migrations.AlterField(
            model_name="dropboxlocation",
            name="address",
            field=models.CharField(default="", max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dropboxlocation",
            name="city",
            field=models.CharField(default="", max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dropboxlocation",
            name="dates_hours",
            field=models.CharField(blank=True, default="", max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dropboxlocation",
            name="location_name",
            field=models.CharField(default="", max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dropboxlocation",
            name="state_code",
            field=models.CharField(
                default="",
                max_length=2,
                validators=[django.core.validators.RegexValidator("^[A-Z]{2}$")],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dropboxlocation",
            name="zip",
            field=models.CharField(
                default="",
                max_length=5,
                validators=[django.core.validators.RegexValidator("^[0-9]{5}$")],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="earlyvotelocation",
            name="address",
            field=models.CharField(default="", max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="earlyvotelocation",
            name="city",
            field=models.CharField(default="", max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="earlyvotelocation",
            name="dates_hours",
            field=models.CharField(blank=True, default="", max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="earlyvotelocation",
            name="location_name",
            field=models.CharField(default="", max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="earlyvotelocation",
            name="state_code",
            field=models.CharField(
                default="",
                max_length=2,
                validators=[django.core.validators.RegexValidator("^[A-Z]{2}$")],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="earlyvotelocation",
            name="zip",
            field=models.CharField(
                default="",
                max_length=5,
                validators=[django.core.validators.RegexValidator("^[0-9]{5}$")],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pollinglocation",
            name="address",
            field=models.CharField(default="", max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pollinglocation",
            name="city",
            field=models.CharField(default="", max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pollinglocation",
            name="dates_hours",
            field=models.CharField(blank=True, default="", max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pollinglocation",
            name="location_name",
            field=models.CharField(default="", max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pollinglocation",
            name="state_code",
            field=models.CharField(
                default="",
                max_length=2,
                validators=[django.core.validators.RegexValidator("^[A-Z]{2}$")],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pollinglocation",
            name="zip",
            field=models.CharField(
                default="",
                max_length=5,
                validators=[django.core.validators.RegexValidator("^[0-9]{5}$")],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="precinct",
            name="precinct_code",
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
