# Generated by Django 2.2.6 on 2020-01-13 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0013_add_constraints")]

    operations = [
        migrations.RemoveConstraint(
            model_name="precincttodropboxlocation",
            name="unique_precinct_dropbox_location",
        ),
        migrations.RemoveConstraint(
            model_name="precincttoevlocation", name="unique_precinct_ev_location"
        ),
        migrations.RemoveConstraint(
            model_name="precincttopollinglocation",
            name="unique_precinct_polling_location",
        ),
        migrations.RenameField(
            model_name="precincttodropboxlocation",
            old_name="dropbox_location",
            new_name="location",
        ),
        migrations.RenameField(
            model_name="precincttoevlocation",
            old_name="early_vote_location",
            new_name="location",
        ),
        migrations.RenameField(
            model_name="precincttopollinglocation",
            old_name="polling_location",
            new_name="location",
        ),
        migrations.AlterField(
            model_name="precincttodropboxlocation",
            name="location",
            field=models.ForeignKey(
                db_column="dropbox_location_id",
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.DropboxLocation",
            ),
        ),
        migrations.AlterField(
            model_name="precincttoevlocation",
            name="location",
            field=models.ForeignKey(
                db_column="early_vote_location_id",
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.EarlyVoteLocation",
            ),
        ),
        migrations.AlterField(
            model_name="precincttopollinglocation",
            name="location",
            field=models.ForeignKey(
                db_column="polling_location_id",
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.PollingLocation",
            ),
        ),
        migrations.AddConstraint(
            model_name="precincttodropboxlocation",
            constraint=models.UniqueConstraint(
                fields=("location", "precinct"), name="unique_precinct_dropbox_location"
            ),
        ),
        migrations.AddConstraint(
            model_name="precincttoevlocation",
            constraint=models.UniqueConstraint(
                fields=("location", "precinct"), name="unique_precinct_ev_location"
            ),
        ),
        migrations.AddConstraint(
            model_name="precincttopollinglocation",
            constraint=models.UniqueConstraint(
                fields=("location", "precinct"), name="unique_precinct_polling_location"
            ),
        ),
    ]
