# Generated by Django 2.2.6 on 2020-01-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0014_rename_location")]

    operations = [
        migrations.AlterField(
            model_name="precincttodropboxlocation",
            name="distance",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="precincttoevlocation",
            name="distance",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="precincttopollinglocation",
            name="distance",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
