# Generated by Django 2.2.6 on 2020-01-24 17:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0015_distance_nullable")]

    operations = [
        migrations.AddField(
            model_name="searchlog",
            name="county",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="searchlog",
            name="other_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="searchlog",
            name="referrer",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="searchlog",
            name="search_id",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="searchlog",
            name="source",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
