# Generated by Django 2.2.6 on 2020-02-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0016_searchlog_additions")]

    operations = [
        migrations.AddField(
            model_name="streetsegment",
            name="confidence_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="zip9toprecinct",
            name="confidence_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
