# Generated by Django 2.2.6 on 2020-02-13 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0017_confidence_score")]

    operations = [
        migrations.CreateModel(
            name="CountyToEVLocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("county", models.CharField(max_length=1024)),
                ("state_code", models.CharField(max_length=2)),
                (
                    "location",
                    models.ForeignKey(
                        db_column="early_vote_location_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.EarlyVoteLocation",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="countytoevlocation",
            constraint=models.UniqueConstraint(
                fields=("location", "county"),
                name="countytoev_unique_county_ev_location",
            ),
        ),
    ]
